# Generated by Django 6.0.6 on 2026-06-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCakeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('occasion', models.CharField(choices=[('Birthday', 'Birthday'), ('Wedding', 'Wedding'), ('Anniversary', 'Anniversary'), ('Baby Shower', 'Baby Shower'), ('Other', 'Other')], max_length=50)),
                ('cake_weight', models.CharField(max_length=50)),
                ('egg_type', models.CharField(max_length=20)),
                ('flavour', models.CharField(max_length=100)),
                ('message_on_cake', models.CharField(blank=True, max_length=255)),
                ('special_note', models.TextField(blank=True)),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='custom_cakes/')),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='New Request', max_length=30)),
            ],
        ),
    ]
