# Generated by Django 6.0.6 on 2026-06-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customcakes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcakerequest',
            name='occasion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customcakerequest',
            name='status',
            field=models.CharField(choices=[('New Request', 'New Request'), ('Contacted', 'Contacted'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New Request', max_length=30),
        ),
    ]
