# Generated by Django 6.0.6 on 2026-07-24 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customcakes', '0002_alter_customcakerequest_occasion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customcakerequest',
            name='egg_type',
        ),
    ]
