"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

import os
from pathlib import Path

from dotenv import load_dotenv


# =========================================================
# BASE DIRECTORY AND ENVIRONMENT VARIABLES
# =========================================================

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# =========================================================
# SECURITY
# =========================================================

SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-change-this-development-key",
)

DEBUG = os.getenv(
    "DJANGO_DEBUG",
    "True",
).lower() in ("true", "1", "yes")

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "DJANGO_ALLOWED_HOSTS",
        "*",
    ).split(",")
    if host.strip()
]


# =========================================================
# APPLICATIONS
# =========================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "core",
    "products",
    "cart",
    "orders",
    "customcakes",
    "accounts",
]


# =========================================================
# MIDDLEWARE
# =========================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# =========================================================
# URL AND TEMPLATE CONFIGURATION
# =========================================================

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": (
            "django.template.backends.django.DjangoTemplates"
        ),
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                (
                    "django.template.context_processors.request"
                ),
                (
                    "django.contrib.auth.context_processors.auth"
                ),
                (
                    "django.contrib.messages.context_processors.messages"
                ),
                "cart.context_processors.cart_counter",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# =========================================================
# DATABASE
# =========================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# =========================================================
# PASSWORD VALIDATION
# =========================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# =========================================================
# INTERNATIONALIZATION
# =========================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# =========================================================
# STATIC AND MEDIA FILES
# =========================================================

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"


# =========================================================
# EMAIL CONFIGURATION
# =========================================================

EMAIL_BACKEND = (
    "django.core.mail.backends.smtp.EmailBackend"
)

EMAIL_HOST = "smtp.gmail.com"

EMAIL_PORT = 587

EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv(
    "EMAIL_HOST_USER",
    "",
)

EMAIL_HOST_PASSWORD = os.getenv(
    "EMAIL_HOST_PASSWORD",
    "",
)

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

ADMIN_EMAIL = os.getenv(
    "ADMIN_EMAIL",
    EMAIL_HOST_USER,
)


# =========================================================
# AUTHENTICATION REDIRECTS
# =========================================================

LOGIN_REDIRECT_URL = "home"

LOGOUT_REDIRECT_URL = "login"

LOGIN_URL = "login"


# =========================================================
# RAZORPAY CONFIGURATION
# =========================================================

RAZORPAY_KEY_ID = os.getenv(
    "RAZORPAY_KEY_ID",
    "",
)

RAZORPAY_KEY_SECRET = os.getenv(
    "RAZORPAY_KEY_SECRET",
    "",
)


# =========================================================
# WHATSAPP CLOUD API CONFIGURATION
# =========================================================

WHATSAPP_API_VERSION = os.getenv(
    "WHATSAPP_API_VERSION",
    "v25.0",
)

WHATSAPP_ACCESS_TOKEN = os.getenv(
    "WHATSAPP_ACCESS_TOKEN",
    "",
)

WHATSAPP_PHONE_NUMBER_ID = os.getenv(
    "WHATSAPP_PHONE_NUMBER_ID",
    "",
)

WHATSAPP_BUSINESS_ACCOUNT_ID = os.getenv(
    "WHATSAPP_BUSINESS_ACCOUNT_ID",
    "",
)

WHATSAPP_NOTIFICATIONS_ENABLED = os.getenv(
    "WHATSAPP_NOTIFICATIONS_ENABLED",
    "False",
).lower() in ("true", "1", "yes")


# Branch phone numbers must contain:
# Country code + mobile number
# Do not add +, spaces or hyphens.
#
# Example:
# 919876543210

BRANCH_WHATSAPP_NUMBERS = {
    # Iyyapanthangal branch 1
    "Iyyapanthangal-1": os.getenv(
        "WHATSAPP_IYYAPANTHANGAL_1_NUMBER",
        "",
    ),
    "Iyyapanthangal 1": os.getenv(
        "WHATSAPP_IYYAPANTHANGAL_1_NUMBER",
        "",
    ),

    # Iyyapanthangal branch 2
    "Iyyapanthangal-2": os.getenv(
        "WHATSAPP_IYYAPANTHANGAL_2_NUMBER",
        "",
    ),
    "Iyyapanthangal 2": os.getenv(
        "WHATSAPP_IYYAPANTHANGAL_2_NUMBER",
        "",
    ),

    # Other branches
    "Porur": os.getenv(
        "WHATSAPP_PORUR_NUMBER",
        "",
    ),
    "Kovur": os.getenv(
        "WHATSAPP_KOVUR_NUMBER",
        "",
    ),
    "Mangadu": os.getenv(
        "WHATSAPP_MANGADU_NUMBER",
        "",
    ),
}

WHATSAPP_ORDER_TEMPLATE_NAME = os.getenv(
    "WHATSAPP_ORDER_TEMPLATE_NAME",
    "cake_spot_new_order",
)

WHATSAPP_ORDER_TEMPLATE_LANGUAGE = os.getenv(
    "WHATSAPP_ORDER_TEMPLATE_LANGUAGE",
    "en",
)