# Generated by Django 6.0.6 on 2026-07-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0008_productaddon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='addon_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='addons',
            field=models.ManyToManyField(blank=True, related_name='cart_items', to='products.productaddon'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='egg_type',
            field=models.CharField(default='Egg', max_length=20),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='weight',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
