# Generated by Django 6.0.6 on 2026-07-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_advance_percentage_order_balance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(choices=[('Kovur', 'Kovur'), ('Porur', 'Porur'), ('Poonamallee', 'Poonamallee'), ('Mangadu', 'Mangadu')], default='Kovur', max_length=50),
            preserve_default=False,
        ),
    ]
