# Generated by Django 6.0.6 on 2026-07-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='whatsapp_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='whatsapp_message_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='whatsapp_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='whatsapp_notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='whatsapp_recipient_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
