# Generated by Django 6.0.6 on 2026-07-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_whatsapp_error_order_whatsapp_message_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.CharField(choices=[('Iyyapanthangal-1', 'Iyyapanthangal-1'), ('Iyyapanthangal-2', 'Iyyapanthangal-2'), ('Porur', 'Porur'), ('Kovur', 'Kovur'), ('Mangadu', 'Mangadu')], max_length=50),
        ),
    ]
