# Generated by Django 6.0.6 on 2026-07-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='egg_type',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='weight',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
