# Generated by Django 6.0.6 on 2026-06-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='intro_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='intro_subtitle',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='category',
            name='intro_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='category',
            name='intro_video',
            field=models.FileField(blank=True, null=True, upload_to='category_videos/'),
        ),
    ]
